source 'https://github.com/CocoaPods/Specs.git'

target 'CollapseClick', :exclusive => true do
  pod "CollapseClick", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CollapseClick", :path => "../"

  
end
