source 'https://github.com/CocoaPods/Specs.git'

target 'STCollapseTableView', :exclusive => true do
  pod "STCollapseTableView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "STCollapseTableView", :path => "../"

  
end
