source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0

target 'TubeIPadApp', :exclusive => true do
  # ________________open projects___________________
  pod "WHTopTabBarController", :path => "../dependencies/lib/WHTopTabBarController"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"

  pod "XCDYouTubeKit", :path => "../dependencies/lib/XCDYouTubeKit"

  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  # ________________Projects for iPad___________________
  pod "YoutubeCollectionView", :path => "../dependencies/ipad/YoutubeCollectionView"

  # ________________module Projects___________________
  pod "VideoWatchDetailViewControlleriPad", :path => "../dependencies/ipad/VideoWatchDetailViewControlleriPad"

end
